module.exports = {
  apps: [
    {
      name: 'obraja-api',
      cwd: '/var/www/obraja/packages/api',
      script: 'dist/main.js',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 3333,
      },
    },
    {
      name: 'obraja-customer',
      cwd: '/var/www/obraja/apps/web-customer',
      script: 'node_modules/.bin/next',
      args: 'start -p 3002',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
    },
    {
      name: 'obraja-seller',
      cwd: '/var/www/obraja/apps/web-seller',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
    },
    {
      name: 'obraja-admin',
      cwd: '/var/www/obraja/apps/web-admin',
      script: 'node_modules/.bin/next',
      args: 'start -p 3001',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '256M',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
    },
  ],
}
